[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "netbox-cots"
version = "0.3.1"
description = "Catalogue COTS, versions et affectations aux rôles pour NetBox 4.4 à 4.7.2"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

[tool.setuptools.packages.find]
include = ["netbox_cots*"]

[tool.setuptools.package-data]
netbox_cots = ["templates/**/*.html"]
