# Generated by Django 6.1.1 on 2026-10-08 14:38

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # Compatible baseline present from NetBox 4.4.0 onward.
    # The table operations are unchanged from 0.1.x; applied installations keep
    # the same migration name and need no schema changes.
    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0132_configcontextprofile'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'COTS',
                'verbose_name_plural': 'COTS',
                'ordering': ('name', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('version', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='netbox_cots.application')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ('application__name', 'version', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='netbox_cots.application')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cots_installations', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cots_installations', to='virtualization.virtualmachine')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='netbox_cots.softwareversion')),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
                'ordering': ('application__name', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='softwareversion',
            constraint=models.UniqueConstraint(fields=('application', 'version'), name='cots_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='installation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('virtual_machine__isnull', True)), models.Q(('device__isnull', True), ('virtual_machine__isnull', False)), _connector='OR'), name='cots_exactly_one_machine'),
        ),
        migrations.AddConstraint(
            model_name='installation',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'application'), name='cots_unique_device_app'),
        ),
        migrations.AddConstraint(
            model_name='installation',
            constraint=models.UniqueConstraint(condition=models.Q(('virtual_machine__isnull', False)), fields=('virtual_machine', 'application'), name='cots_unique_vm_app'),
        ),
    ]
