# Generated by Django 5.2.5 on 2026-10-09 09:17

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0132_configcontextprofile'),
        ('netbox_cots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='netbox_cots.application')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cots_assignments', to='dcim.devicerole')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='netbox_cots.softwareversion')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Affectation au rôle',
                'verbose_name_plural': 'Affectations aux rôles',
                'ordering': ('role__name', 'application__name', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('role', 'application'), name='cots_unique_role_app')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
